name = "lutnita"
compatibility_date = "2025-07-31"

[build]
command = "chmod a+x build.sh && ./build.sh"

[assets]
directory = "./public"
html_handling = "force-trailing-slash"
not_found_handling = "404-page"